### ISSUE TITLE
Chemical Get All

### ISSUE THREAD

**Issue by timothyhollabaugh** [A-Team-Rowan-University/WebdevFrontend#5]
Should be able to copy from the users

**Comment by penatem1** [comment]
Back end implemented, structure is ordered and defined as follows:
Name | Type :
- id | unsigned 64 bit integer
- name | String
- purpose | String

**Comment by penatem1** [comment]
Added more fields:
Name | Type

- company_name | String
- ingredients | String
- manual_link | String
